name: dialogix_ai
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#610094"


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
